// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: proto/order_history.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	ProductIds    []string               `protobuf:"bytes,4,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	Total         float64                `protobuf:"fixed64,5,opt,name=total,proto3" json:"total,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_order_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Order) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *Order) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Order) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type AddOrderHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderHistoryRequest) Reset() {
	*x = AddOrderHistoryRequest{}
	mi := &file_proto_order_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderHistoryRequest) ProtoMessage() {}

func (x *AddOrderHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderHistoryRequest.ProtoReflect.Descriptor instead.
func (*AddOrderHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{1}
}

func (x *AddOrderHistoryRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *AddOrderHistoryRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AddOrderHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderHistoryResponse) Reset() {
	*x = AddOrderHistoryResponse{}
	mi := &file_proto_order_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderHistoryResponse) ProtoMessage() {}

func (x *AddOrderHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderHistoryResponse.ProtoReflect.Descriptor instead.
func (*AddOrderHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{2}
}

func (x *AddOrderHistoryResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderHistoryRequest) Reset() {
	*x = GetOrderHistoryRequest{}
	mi := &file_proto_order_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderHistoryRequest) ProtoMessage() {}

func (x *GetOrderHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetOrderHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetOrderHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderHistoryResponse) Reset() {
	*x = GetOrderHistoryResponse{}
	mi := &file_proto_order_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderHistoryResponse) ProtoMessage() {}

func (x *GetOrderHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetOrderHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderHistoryResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetOrderByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdRequest) Reset() {
	*x = GetOrderByIdRequest{}
	mi := &file_proto_order_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdRequest) ProtoMessage() {}

func (x *GetOrderByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderByIdRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdResponse) Reset() {
	*x = GetOrderByIdResponse{}
	mi := &file_proto_order_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdResponse) ProtoMessage() {}

func (x *GetOrderByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderByIdResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ReorderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderRequest) Reset() {
	*x = ReorderRequest{}
	mi := &file_proto_order_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderRequest) ProtoMessage() {}

func (x *ReorderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderRequest.ProtoReflect.Descriptor instead.
func (*ReorderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{7}
}

func (x *ReorderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ReorderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderResponse) Reset() {
	*x = ReorderResponse{}
	mi := &file_proto_order_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderResponse) ProtoMessage() {}

func (x *ReorderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderResponse.ProtoReflect.Descriptor instead.
func (*ReorderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{8}
}

func (x *ReorderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type DeleteOrderHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderHistoryRequest) Reset() {
	*x = DeleteOrderHistoryRequest{}
	mi := &file_proto_order_history_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderHistoryRequest) ProtoMessage() {}

func (x *DeleteOrderHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderHistoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteOrderHistoryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type DeleteOrderHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderHistoryResponse) Reset() {
	*x = DeleteOrderHistoryResponse{}
	mi := &file_proto_order_history_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderHistoryResponse) ProtoMessage() {}

func (x *DeleteOrderHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderHistoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrderHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteOrderHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRecentOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentOrdersRequest) Reset() {
	*x = GetRecentOrdersRequest{}
	mi := &file_proto_order_history_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentOrdersRequest) ProtoMessage() {}

func (x *GetRecentOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetRecentOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{11}
}

func (x *GetRecentOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecentOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRecentOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentOrdersResponse) Reset() {
	*x = GetRecentOrdersResponse{}
	mi := &file_proto_order_history_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentOrdersResponse) ProtoMessage() {}

func (x *GetRecentOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_history_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetRecentOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_history_proto_rawDescGZIP(), []int{12}
}

func (x *GetRecentOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_proto_order_history_proto protoreflect.FileDescriptor

const file_proto_order_history_proto_rawDesc = "" +
	"\n" +
	"\x19proto/order_history.proto\x12\forderhistory\"\xac\x01\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1f\n" +
	"\vproduct_ids\x18\x04 \x03(\tR\n" +
	"productIds\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x01R\x05total\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"_\n" +
	"\x16AddOrderHistoryRequest\x12)\n" +
	"\x05order\x18\x01 \x01(\v2\x13.orderhistory.OrderR\x05order\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"D\n" +
	"\x17AddOrderHistoryResponse\x12)\n" +
	"\x05order\x18\x01 \x01(\v2\x13.orderhistory.OrderR\x05order\"1\n" +
	"\x16GetOrderHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x17GetOrderHistoryResponse\x12+\n" +
	"\x06orders\x18\x01 \x03(\v2\x13.orderhistory.OrderR\x06orders\"0\n" +
	"\x13GetOrderByIdRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"A\n" +
	"\x14GetOrderByIdResponse\x12)\n" +
	"\x05order\x18\x01 \x01(\v2\x13.orderhistory.OrderR\x05order\"+\n" +
	"\x0eReorderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"<\n" +
	"\x0fReorderResponse\x12)\n" +
	"\x05order\x18\x01 \x01(\v2\x13.orderhistory.OrderR\x05order\"6\n" +
	"\x19DeleteOrderHistoryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"6\n" +
	"\x1aDeleteOrderHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"G\n" +
	"\x16GetRecentOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"F\n" +
	"\x17GetRecentOrdersResponse\x12+\n" +
	"\x06orders\x18\x01 \x03(\v2\x13.orderhistory.OrderR\x06orders2\xbd\x04\n" +
	"\x13OrderHistoryService\x12^\n" +
	"\x0fAddOrderHistory\x12$.orderhistory.AddOrderHistoryRequest\x1a%.orderhistory.AddOrderHistoryResponse\x12^\n" +
	"\x0fGetOrderHistory\x12$.orderhistory.GetOrderHistoryRequest\x1a%.orderhistory.GetOrderHistoryResponse\x12U\n" +
	"\fGetOrderById\x12!.orderhistory.GetOrderByIdRequest\x1a\".orderhistory.GetOrderByIdResponse\x12F\n" +
	"\aReorder\x12\x1c.orderhistory.ReorderRequest\x1a\x1d.orderhistory.ReorderResponse\x12g\n" +
	"\x12DeleteOrderHistory\x12'.orderhistory.DeleteOrderHistoryRequest\x1a(.orderhistory.DeleteOrderHistoryResponse\x12^\n" +
	"\x0fGetRecentOrders\x12$.orderhistory.GetRecentOrdersRequest\x1a%.orderhistory.GetRecentOrdersResponseB.Z,meaningfullname/Yurt_Mart/orderhistory/protob\x06proto3"

var (
	file_proto_order_history_proto_rawDescOnce sync.Once
	file_proto_order_history_proto_rawDescData []byte
)

func file_proto_order_history_proto_rawDescGZIP() []byte {
	file_proto_order_history_proto_rawDescOnce.Do(func() {
		file_proto_order_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_history_proto_rawDesc), len(file_proto_order_history_proto_rawDesc)))
	})
	return file_proto_order_history_proto_rawDescData
}

var file_proto_order_history_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_order_history_proto_goTypes = []any{
	(*Order)(nil),                      // 0: orderhistory.Order
	(*AddOrderHistoryRequest)(nil),     // 1: orderhistory.AddOrderHistoryRequest
	(*AddOrderHistoryResponse)(nil),    // 2: orderhistory.AddOrderHistoryResponse
	(*GetOrderHistoryRequest)(nil),     // 3: orderhistory.GetOrderHistoryRequest
	(*GetOrderHistoryResponse)(nil),    // 4: orderhistory.GetOrderHistoryResponse
	(*GetOrderByIdRequest)(nil),        // 5: orderhistory.GetOrderByIdRequest
	(*GetOrderByIdResponse)(nil),       // 6: orderhistory.GetOrderByIdResponse
	(*ReorderRequest)(nil),             // 7: orderhistory.ReorderRequest
	(*ReorderResponse)(nil),            // 8: orderhistory.ReorderResponse
	(*DeleteOrderHistoryRequest)(nil),  // 9: orderhistory.DeleteOrderHistoryRequest
	(*DeleteOrderHistoryResponse)(nil), // 10: orderhistory.DeleteOrderHistoryResponse
	(*GetRecentOrdersRequest)(nil),     // 11: orderhistory.GetRecentOrdersRequest
	(*GetRecentOrdersResponse)(nil),    // 12: orderhistory.GetRecentOrdersResponse
}
var file_proto_order_history_proto_depIdxs = []int32{
	0,  // 0: orderhistory.AddOrderHistoryRequest.order:type_name -> orderhistory.Order
	0,  // 1: orderhistory.AddOrderHistoryResponse.order:type_name -> orderhistory.Order
	0,  // 2: orderhistory.GetOrderHistoryResponse.orders:type_name -> orderhistory.Order
	0,  // 3: orderhistory.GetOrderByIdResponse.order:type_name -> orderhistory.Order
	0,  // 4: orderhistory.ReorderResponse.order:type_name -> orderhistory.Order
	0,  // 5: orderhistory.GetRecentOrdersResponse.orders:type_name -> orderhistory.Order
	1,  // 6: orderhistory.OrderHistoryService.AddOrderHistory:input_type -> orderhistory.AddOrderHistoryRequest
	3,  // 7: orderhistory.OrderHistoryService.GetOrderHistory:input_type -> orderhistory.GetOrderHistoryRequest
	5,  // 8: orderhistory.OrderHistoryService.GetOrderById:input_type -> orderhistory.GetOrderByIdRequest
	7,  // 9: orderhistory.OrderHistoryService.Reorder:input_type -> orderhistory.ReorderRequest
	9,  // 10: orderhistory.OrderHistoryService.DeleteOrderHistory:input_type -> orderhistory.DeleteOrderHistoryRequest
	11, // 11: orderhistory.OrderHistoryService.GetRecentOrders:input_type -> orderhistory.GetRecentOrdersRequest
	2,  // 12: orderhistory.OrderHistoryService.AddOrderHistory:output_type -> orderhistory.AddOrderHistoryResponse
	4,  // 13: orderhistory.OrderHistoryService.GetOrderHistory:output_type -> orderhistory.GetOrderHistoryResponse
	6,  // 14: orderhistory.OrderHistoryService.GetOrderById:output_type -> orderhistory.GetOrderByIdResponse
	8,  // 15: orderhistory.OrderHistoryService.Reorder:output_type -> orderhistory.ReorderResponse
	10, // 16: orderhistory.OrderHistoryService.DeleteOrderHistory:output_type -> orderhistory.DeleteOrderHistoryResponse
	12, // 17: orderhistory.OrderHistoryService.GetRecentOrders:output_type -> orderhistory.GetRecentOrdersResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_order_history_proto_init() }
func file_proto_order_history_proto_init() {
	if File_proto_order_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_history_proto_rawDesc), len(file_proto_order_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_history_proto_goTypes,
		DependencyIndexes: file_proto_order_history_proto_depIdxs,
		MessageInfos:      file_proto_order_history_proto_msgTypes,
	}.Build()
	File_proto_order_history_proto = out.File
	file_proto_order_history_proto_goTypes = nil
	file_proto_order_history_proto_depIdxs = nil
}
