#version: '3.8'
#
#services:
#  nats:
#    image: nats:latest
#    ports:
#      - "4222:4222"
#    volumes:
#      - ./nats-config/nats.conf:/nats.conf
#    command: ["-c", "/nats.conf"]
#
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#
#  mongodb:
#    image: mongo:latest
#    container_name: user_service_mongodb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongodb_data:/data/db
#
#volumes:
#  mongodb_data: