version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    volumes:
      - ./nats-config/nats.conf:/nats.conf
    command: ["-c", "/nats.conf"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: user_service_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    environment:
      - PORT=50052
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - MONGO_URI=mongodb://user_service_mongodb:27017
      - MONGO_DB=payments
      - NATS_URL=nats://nats:4222
      - JWT_SECRET=your-secret-key
      - RATE_LIMIT=60
      - RATE_LIMIT_BURST=10
      - STRIPE_SECRET_KEY=sk_test_xxx
      - ETHEREUM_RPC=https://mainnet.infura.io/v3/your-project-id
    depends_on:
      - mongodb
      - redis
      - nats
    ports:
      - "50052:50052"

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    environment:
      - PORT=50051
      - MONGO_URI=mongodb://user_service_mongodb:27017
      - MONGO_DB=orders
      - NATS_URL=nats://nats:4222
    depends_on:
      - mongodb
      - nats
    ports:
      - "50051:50051"

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    environment:
      - PORT=50053
      - MONGO_URI=mongodb://user_service_mongodb:27017
      - MONGO_DB=users
      - NATS_URL=nats://nats:4222
    depends_on:
      - mongodb
      - nats
    ports:
      - "50053:50053"

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    environment:
      - PORT=50054
      - MONGO_URI=mongodb://user_service_mongodb:27017
      - MONGO_DB=products
      - NATS_URL=nats://nats:4222
    depends_on:
      - mongodb
      - nats
    ports:
      - "50054:50054"

  shopping-cart-service:
    build:
      context: ./shopping-cart-service
    container_name: shopping-cart-service
    environment:
      - PORT=50055
      - MONGO_URI=mongodb://user_service_mongodb:27017
      - MONGO_DB=cart
      - NATS_URL=nats://nats:4222
    depends_on:
      - mongodb
      - nats
    ports:
      - "50055:50055"

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      - PORT=8080
      - ORDER_SERVICE_ADDR=order-service:50051
      - USER_SERVICE_ADDR=user-service:50053
      - PRODUCT_SERVICE_ADDR=product-service:50054
      - PAYMENT_SERVICE_ADDR=payment-service:50052
      - CART_SERVICE_ADDR=shopping-cart-service:50055
    depends_on:
      - order-service
      - user-service
      - product-service
      - payment-service
      - shopping-cart-service
    ports:
      - "8080:8080"

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:
