global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8080']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8080']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8080']

  - job_name: 'shopping-cart-service'
    static_configs:
      - targets: ['shopping-cart-service:8080'] 