// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: review/proto/review.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_review_proto_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{0}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Review) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_review_proto_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReviewRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateReviewRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CreateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewResponse) Reset() {
	*x = CreateReviewResponse{}
	mi := &file_review_proto_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewResponse) ProtoMessage() {}

func (x *CreateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewResponse.ProtoReflect.Descriptor instead.
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type GetProductReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReviewsRequest) Reset() {
	*x = GetProductReviewsRequest{}
	mi := &file_review_proto_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReviewsRequest) ProtoMessage() {}

func (x *GetProductReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetProductReviewsRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductReviewsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetProductReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReviewsResponse) Reset() {
	*x = GetProductReviewsResponse{}
	mi := &file_review_proto_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReviewsResponse) ProtoMessage() {}

func (x *GetProductReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetProductReviewsResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type GetUserReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReviewsRequest) Reset() {
	*x = GetUserReviewsRequest{}
	mi := &file_review_proto_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReviewsRequest) ProtoMessage() {}

func (x *GetUserReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetUserReviewsRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserReviewsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReviewsResponse) Reset() {
	*x = GetUserReviewsResponse{}
	mi := &file_review_proto_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReviewsResponse) ProtoMessage() {}

func (x *GetUserReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetUserReviewsResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type UpdateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      string                 `protobuf:"bytes,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReviewRequest) Reset() {
	*x = UpdateReviewRequest{}
	mi := &file_review_proto_review_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReviewRequest) ProtoMessage() {}

func (x *UpdateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReviewRequest.ProtoReflect.Descriptor instead.
func (*UpdateReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateReviewRequest) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

func (x *UpdateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UpdateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type UpdateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReviewResponse) Reset() {
	*x = UpdateReviewResponse{}
	mi := &file_review_proto_review_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReviewResponse) ProtoMessage() {}

func (x *UpdateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReviewResponse.ProtoReflect.Descriptor instead.
func (*UpdateReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      string                 `protobuf:"bytes,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_review_proto_review_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteReviewRequest) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

type DeleteReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewResponse) Reset() {
	*x = DeleteReviewResponse{}
	mi := &file_review_proto_review_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewResponse) ProtoMessage() {}

func (x *DeleteReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewResponse.ProtoReflect.Descriptor instead.
func (*DeleteReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteReviewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAverageProductRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAverageProductRatingRequest) Reset() {
	*x = GetAverageProductRatingRequest{}
	mi := &file_review_proto_review_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAverageProductRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageProductRatingRequest) ProtoMessage() {}

func (x *GetAverageProductRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageProductRatingRequest.ProtoReflect.Descriptor instead.
func (*GetAverageProductRatingRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{11}
}

func (x *GetAverageProductRatingRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetAverageProductRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AverageRating float64                `protobuf:"fixed64,1,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAverageProductRatingResponse) Reset() {
	*x = GetAverageProductRatingResponse{}
	mi := &file_review_proto_review_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAverageProductRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageProductRatingResponse) ProtoMessage() {}

func (x *GetAverageProductRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_review_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageProductRatingResponse.ProtoReflect.Descriptor instead.
func (*GetAverageProductRatingResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_review_proto_rawDescGZIP(), []int{12}
}

func (x *GetAverageProductRatingResponse) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

var File_review_proto_review_proto protoreflect.FileDescriptor

const file_review_proto_review_proto_rawDesc = "" +
	"\n" +
	"\x19review/proto/review.proto\x12\x06review\"\xa0\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"\x7f\n" +
	"\x13CreateReviewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\">\n" +
	"\x14CreateReviewResponse\x12&\n" +
	"\x06review\x18\x01 \x01(\v2\x0e.review.ReviewR\x06review\"9\n" +
	"\x18GetProductReviewsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"E\n" +
	"\x19GetProductReviewsResponse\x12(\n" +
	"\areviews\x18\x01 \x03(\v2\x0e.review.ReviewR\areviews\"0\n" +
	"\x15GetUserReviewsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"B\n" +
	"\x16GetUserReviewsResponse\x12(\n" +
	"\areviews\x18\x01 \x03(\v2\x0e.review.ReviewR\areviews\"d\n" +
	"\x13UpdateReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\tR\breviewId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\">\n" +
	"\x14UpdateReviewResponse\x12&\n" +
	"\x06review\x18\x01 \x01(\v2\x0e.review.ReviewR\x06review\"2\n" +
	"\x13DeleteReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\tR\breviewId\"0\n" +
	"\x14DeleteReviewResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x1eGetAverageProductRatingRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"H\n" +
	"\x1fGetAverageProductRatingResponse\x12%\n" +
	"\x0eaverage_rating\x18\x01 \x01(\x01R\raverageRating2\x87\x04\n" +
	"\rReviewService\x12I\n" +
	"\fCreateReview\x12\x1b.review.CreateReviewRequest\x1a\x1c.review.CreateReviewResponse\x12X\n" +
	"\x11GetProductReviews\x12 .review.GetProductReviewsRequest\x1a!.review.GetProductReviewsResponse\x12O\n" +
	"\x0eGetUserReviews\x12\x1d.review.GetUserReviewsRequest\x1a\x1e.review.GetUserReviewsResponse\x12I\n" +
	"\fUpdateReview\x12\x1b.review.UpdateReviewRequest\x1a\x1c.review.UpdateReviewResponse\x12I\n" +
	"\fDeleteReview\x12\x1b.review.DeleteReviewRequest\x1a\x1c.review.DeleteReviewResponse\x12j\n" +
	"\x17GetAverageProductRating\x12&.review.GetAverageProductRatingRequest\x1a'.review.GetAverageProductRatingResponseB(Z&meaningfullname/Yurt_Mart/review/protob\x06proto3"

var (
	file_review_proto_review_proto_rawDescOnce sync.Once
	file_review_proto_review_proto_rawDescData []byte
)

func file_review_proto_review_proto_rawDescGZIP() []byte {
	file_review_proto_review_proto_rawDescOnce.Do(func() {
		file_review_proto_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_proto_review_proto_rawDesc), len(file_review_proto_review_proto_rawDesc)))
	})
	return file_review_proto_review_proto_rawDescData
}

var file_review_proto_review_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_review_proto_review_proto_goTypes = []any{
	(*Review)(nil),                          // 0: review.Review
	(*CreateReviewRequest)(nil),             // 1: review.CreateReviewRequest
	(*CreateReviewResponse)(nil),            // 2: review.CreateReviewResponse
	(*GetProductReviewsRequest)(nil),        // 3: review.GetProductReviewsRequest
	(*GetProductReviewsResponse)(nil),       // 4: review.GetProductReviewsResponse
	(*GetUserReviewsRequest)(nil),           // 5: review.GetUserReviewsRequest
	(*GetUserReviewsResponse)(nil),          // 6: review.GetUserReviewsResponse
	(*UpdateReviewRequest)(nil),             // 7: review.UpdateReviewRequest
	(*UpdateReviewResponse)(nil),            // 8: review.UpdateReviewResponse
	(*DeleteReviewRequest)(nil),             // 9: review.DeleteReviewRequest
	(*DeleteReviewResponse)(nil),            // 10: review.DeleteReviewResponse
	(*GetAverageProductRatingRequest)(nil),  // 11: review.GetAverageProductRatingRequest
	(*GetAverageProductRatingResponse)(nil), // 12: review.GetAverageProductRatingResponse
}
var file_review_proto_review_proto_depIdxs = []int32{
	0,  // 0: review.CreateReviewResponse.review:type_name -> review.Review
	0,  // 1: review.GetProductReviewsResponse.reviews:type_name -> review.Review
	0,  // 2: review.GetUserReviewsResponse.reviews:type_name -> review.Review
	0,  // 3: review.UpdateReviewResponse.review:type_name -> review.Review
	1,  // 4: review.ReviewService.CreateReview:input_type -> review.CreateReviewRequest
	3,  // 5: review.ReviewService.GetProductReviews:input_type -> review.GetProductReviewsRequest
	5,  // 6: review.ReviewService.GetUserReviews:input_type -> review.GetUserReviewsRequest
	7,  // 7: review.ReviewService.UpdateReview:input_type -> review.UpdateReviewRequest
	9,  // 8: review.ReviewService.DeleteReview:input_type -> review.DeleteReviewRequest
	11, // 9: review.ReviewService.GetAverageProductRating:input_type -> review.GetAverageProductRatingRequest
	2,  // 10: review.ReviewService.CreateReview:output_type -> review.CreateReviewResponse
	4,  // 11: review.ReviewService.GetProductReviews:output_type -> review.GetProductReviewsResponse
	6,  // 12: review.ReviewService.GetUserReviews:output_type -> review.GetUserReviewsResponse
	8,  // 13: review.ReviewService.UpdateReview:output_type -> review.UpdateReviewResponse
	10, // 14: review.ReviewService.DeleteReview:output_type -> review.DeleteReviewResponse
	12, // 15: review.ReviewService.GetAverageProductRating:output_type -> review.GetAverageProductRatingResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_review_proto_review_proto_init() }
func file_review_proto_review_proto_init() {
	if File_review_proto_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_proto_review_proto_rawDesc), len(file_review_proto_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_proto_review_proto_goTypes,
		DependencyIndexes: file_review_proto_review_proto_depIdxs,
		MessageInfos:      file_review_proto_review_proto_msgTypes,
	}.Build()
	File_review_proto_review_proto = out.File
	file_review_proto_review_proto_goTypes = nil
	file_review_proto_review_proto_depIdxs = nil
}
